targets = [ "//:msm" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-parameter"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-proto"
version = "branch=master"
