manifest = "b52ad189987f35817307f0cd78e2d9e5e950845e9315c8bc06c8b4e90e7c242d"

[[dependency]]
package = "github.com/buckaroo-pm/boost-parameter"
target = "//:parameter"

[lock."github.com/buckaroo-pm/boost-parameter"]
versions = [ "branch=master" ]
revision = "292c3e063e8d44d4a967b70939a8a56d6c48d297"
