manifest = "63abef2b1a2425083d66d758199982ad271d4a1f03421383b6d3e8f41bc91f95"

[[dependency]]
package = "github.com/buckaroo-pm/boost-parameter"
target = "//:parameter"

[[dependency]]
package = "github.com/buckaroo-pm/boost-proto"
target = "//:proto"

[lock."github.com/buckaroo-pm/boost-parameter"]
versions = [ "branch=master" ]
revision = "292c3e063e8d44d4a967b70939a8a56d6c48d297"

[lock."github.com/buckaroo-pm/boost-proto"]
versions = [ "branch=master" ]
revision = "153d707e0fbf7ea9898d5566e56264f0b181e320"
